name: scraping
channels:
  - conda-forge
dependencies:
  - python=3.10
  - geckodriver
  - isoduration
  - orjson
  - pandas
  - polars
  - seaborn
  - tenacity

  # https://github.com/conda/conda-lock/issues/413
  # Requires installing conda-lock from GitHub (in conda base environment)
  # $ python -m pip install git+https://github.com/conda/conda-lock.git   
  - pip:
    - arsenic
    - price-parser
platforms:
  - linux-64
